language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=21
  - ANDROID_BUILD_TOOLS_VERSION=21.0.1
  - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools # to get the new `repository-11.xml`
  - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
  - platform-tools
  - build-tools-27.0.3
  - android-27
before_install:
  - yes | sdkmanager "platforms;android-27"
script:
  - ./gradlew build connectedCheck
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"