language: android
android:
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-28
    - android-24
    - sys-img-armeabi-v7a-android-24
before_install:
  - yes | sdkmanager "platforms;android-28"
before_script:
  # Prepare pre-accepted licenses to not be prompted at installation
  - mkdir -p "$ANDROID_HOME/licenses"
  - cp ./google-licenses/* "$ANDROID_HOME/licenses/"
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

